### ISSUE TITLE
Fatal error using with "API" search keyword

### ISSUE THREAD

**Issue by kododebagga** [WebberZone/better-search#99] opened 2023-04-11 17:05 UTC
Hello,

When using `API` as the search keyword the WordPress instance is getting a fatal error. All other plugins have been disabled.

We're running **PHP 8.1** and **WordPress 6.2**.

If `DEBUG` mode is enabled then the error message looks like this:

~~~
Fatal error: Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, int given in /home/domain/public_html/wp-content/plugins/better-search/includes/class-better-search.php:1035 Stack trace: #0 /home/domain/public_html/wp-content/plugins/better-search/includes/class-better-search.php(1035): in_array() #1 /home/domain/public_html/wp-content/plugins/better-search/includes/class-better-search.php(571): Better_Search->parse_search_terms() #2 /home/domain/public_html/wp-includes/class-wp-hook.php(308): Better_Search->posts_search() #3 /home/domain/public_html/wp-includes/plugin.php(256): WP_Hook->apply_filters() #4 /home/domain/public_html/wp-includes/class-wp-query.php(2229): apply_filters_ref_array() #5 /home/domain/public_html/wp-includes/class-wp-query.php(3787): WP_Query->get_posts() #6 /home/domain/public_html/wp-includes/class-wp-query.php(3919): WP_Query->query() #7 /home/domain/public_html/wp-content/plugins/better-search/includes/class-better-search-query.php(44): WP_Query->__construct() #8 /home/domain/public_html/wp-content/plugins/better-search/templates/template.php(43): Better_Search_Query->__construct() #9 /home/domain/public_html/wp-includes/template-loader.php(106): include('...') #10 /home/domain/public_html/wp-blog-header.php(19): require_once('...') #11 /home/domain/public_html/index.php(17): require('...') #12 {main} thrown in /home/domain/public_html/wp-content/plugins/better-search/includes/class-better-search.php on line 1035
There has been a critical error on this website.
~~~

We could fix it locally by changing line `1035` in the mentioned `plugins/better-search/includes/class-better-search.php` file to:

```
if ( $stopwords && in_array( call_user_func( $strtolower, $term ), $stopwords, true ) ) {
     continue;
}
```

Although, the source of the issue could be something else.

**Comment by ajaydsouza** [comment] 2023-04-11 17:54
Duplicate of https://github.com/WebberZone/better-search/issues/97

I will fix in the next version

**Comment by iliajie** [comment] 2023-04-11 20:13
> Please can you check this beta?
> 
> https://github.com/WebberZone/better-search/releases/tag/v3.2.1-beta1

That seems to work. Thanks!

**Comment by donbowman** [comment] 2023-04-13 02:00
> Please can you check this beta?
> 
> https://github.com/WebberZone/better-search/releases/tag/v3.2.1-beta1

this resolves for me.

**Closed** 2023-04-13 18:01 UTC
